### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by raghavddps2** [raghavddps2/Basic-Blog-Application-in-Flask#6]
Provide a complete guide as to how can a person, follow up and use the basic bolier plate in his/her code

**Comment by rblcoder** [comment]
Hi @raghavddps2 , I have forked your repository, https://github.com/rblcoder/Basic-Blog-Application-in-Flask, made a few changes and written the steps I followed to run the application. Would you like these to be merged into your repository? Should I create a pull request for the same?

**Comment by raghavddps2** [comment]
> Hi @raghavddps2 , I have forked your repository, https://github.com/rblcoder/Basic-Blog-Application-in-Flask, made a few changes and written the steps I followed to run the application. Would you like these to be merged into your repository? Should I create a pull request for the same?

Hey, you just did an awesome job. Though some of the things like dockerfile one, i have no idea about. I just know that its some devops stuff. But you just made it a perfect boilerplate for anyone. Thank you so much. I learnt many things from what you did. 

Just create a pull request and i will surely merge it.

**Comment by rblcoder** [comment]
Thanks a lot @raghavddps2 , I have created a pull request. It was good working on this. Thank you.
